/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as AuthPinSetupRouteImport } from './routes/auth.pin-setup'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppWithdrawRouteImport } from './routes/_app.withdraw'
import { Route as AppTransferRouteImport } from './routes/_app.transfer'
import { Route as AppTendersRouteImport } from './routes/_app.tenders'
import { Route as AppStatementsRouteImport } from './routes/_app.statements'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppSponsorshipsRouteImport } from './routes/_app.sponsorships'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppOffersRouteImport } from './routes/_app.offers'
import { Route as AppLoansRouteImport } from './routes/_app.loans'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppGuarantorsRouteImport } from './routes/_app.guarantors'
import { Route as AppGroupsRouteImport } from './routes/_app.groups'
import { Route as AppGlAccountsRouteImport } from './routes/_app.gl-accounts'
import { Route as AppClassGroupsRouteImport } from './routes/_app.class-groups'
import { Route as AppCardsRouteImport } from './routes/_app.cards'
import { Route as AppBusinessRouteImport } from './routes/_app.business'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppLoansApplyRouteImport } from './routes/_app.loans.apply'
import { Route as AppDevStatementRouteImport } from './routes/_app.dev.statement'
import { Route as AppDevEmailsRouteImport } from './routes/_app.dev.emails'
import { Route as AppBusinessIdRouteImport } from './routes/_app.business.$id'
import { Route as AdminAdminTransactionsRouteImport } from './routes/_admin.admin.transactions'
import { Route as AdminAdminMembersRouteImport } from './routes/_admin.admin.members'
import { Route as AdminAdminLoansRouteImport } from './routes/_admin.admin.loans'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminApprovalsRouteImport } from './routes/_admin.admin.approvals'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPinSetupRoute = AuthPinSetupRouteImport.update({
  id: '/auth/pin-setup',
  path: '/auth/pin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppTendersRoute = AppTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSponsorshipsRoute = AppSponsorshipsRouteImport.update({
  id: '/sponsorships',
  path: '/sponsorships',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppGuarantorsRoute = AppGuarantorsRouteImport.update({
  id: '/guarantors',
  path: '/guarantors',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppGlAccountsRoute = AppGlAccountsRouteImport.update({
  id: '/gl-accounts',
  path: '/gl-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppClassGroupsRoute = AppClassGroupsRouteImport.update({
  id: '/class-groups',
  path: '/class-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansApplyRoute = AppLoansApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AppLoansRoute,
} as any)
const AppDevStatementRoute = AppDevStatementRouteImport.update({
  id: '/dev/statement',
  path: '/dev/statement',
  getParentRoute: () => AppRoute,
} as any)
const AppDevEmailsRoute = AppDevEmailsRouteImport.update({
  id: '/dev/emails',
  path: '/dev/emails',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessIdRoute = AppBusinessIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBusinessRoute,
} as any)
const AdminAdminTransactionsRoute = AdminAdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMembersRoute = AdminAdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLoansRoute = AdminAdminLoansRouteImport.update({
  id: '/admin/loans',
  path: '/admin/loans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminApprovalsRoute = AdminAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRoute
  '/business': typeof AppBusinessRouteWithChildren
  '/cards': typeof AppCardsRoute
  '/class-groups': typeof AppClassGroupsRoute
  '/gl-accounts': typeof AppGlAccountsRoute
  '/groups': typeof AppGroupsRoute
  '/guarantors': typeof AppGuarantorsRoute
  '/jobs': typeof AppJobsRoute
  '/loans': typeof AppLoansRouteWithChildren
  '/offers': typeof AppOffersRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/sponsorships': typeof AppSponsorshipsRoute
  '/staff': typeof AppStaffRoute
  '/statements': typeof AppStatementsRoute
  '/tenders': typeof AppTendersRoute
  '/transfer': typeof AppTransferRoute
  '/withdraw': typeof AppWithdrawRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/pin-setup': typeof AuthPinSetupRoute
  '/p/$id': typeof PIdRoute
  '/admin/approvals': typeof AdminAdminApprovalsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/loans': typeof AdminAdminLoansRoute
  '/admin/members': typeof AdminAdminMembersRoute
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/business/$id': typeof AppBusinessIdRoute
  '/dev/emails': typeof AppDevEmailsRoute
  '/dev/statement': typeof AppDevStatementRoute
  '/loans/apply': typeof AppLoansApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRoute
  '/business': typeof AppBusinessRouteWithChildren
  '/cards': typeof AppCardsRoute
  '/class-groups': typeof AppClassGroupsRoute
  '/gl-accounts': typeof AppGlAccountsRoute
  '/groups': typeof AppGroupsRoute
  '/guarantors': typeof AppGuarantorsRoute
  '/jobs': typeof AppJobsRoute
  '/loans': typeof AppLoansRouteWithChildren
  '/offers': typeof AppOffersRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/sponsorships': typeof AppSponsorshipsRoute
  '/staff': typeof AppStaffRoute
  '/statements': typeof AppStatementsRoute
  '/tenders': typeof AppTendersRoute
  '/transfer': typeof AppTransferRoute
  '/withdraw': typeof AppWithdrawRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/pin-setup': typeof AuthPinSetupRoute
  '/p/$id': typeof PIdRoute
  '/admin/approvals': typeof AdminAdminApprovalsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/loans': typeof AdminAdminLoansRoute
  '/admin/members': typeof AdminAdminMembersRoute
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/business/$id': typeof AppBusinessIdRoute
  '/dev/emails': typeof AppDevEmailsRoute
  '/dev/statement': typeof AppDevStatementRoute
  '/loans/apply': typeof AppLoansApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/business': typeof AppBusinessRouteWithChildren
  '/_app/cards': typeof AppCardsRoute
  '/_app/class-groups': typeof AppClassGroupsRoute
  '/_app/gl-accounts': typeof AppGlAccountsRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/guarantors': typeof AppGuarantorsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/loans': typeof AppLoansRouteWithChildren
  '/_app/offers': typeof AppOffersRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sponsorships': typeof AppSponsorshipsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/statements': typeof AppStatementsRoute
  '/_app/tenders': typeof AppTendersRoute
  '/_app/transfer': typeof AppTransferRoute
  '/_app/withdraw': typeof AppWithdrawRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/pin-setup': typeof AuthPinSetupRoute
  '/p/$id': typeof PIdRoute
  '/_app/': typeof AppIndexRoute
  '/_admin/admin/approvals': typeof AdminAdminApprovalsRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/loans': typeof AdminAdminLoansRoute
  '/_admin/admin/members': typeof AdminAdminMembersRoute
  '/_admin/admin/transactions': typeof AdminAdminTransactionsRoute
  '/_app/business/$id': typeof AppBusinessIdRoute
  '/_app/dev/emails': typeof AppDevEmailsRoute
  '/_app/dev/statement': typeof AppDevStatementRoute
  '/_app/loans/apply': typeof AppLoansApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/business'
    | '/cards'
    | '/class-groups'
    | '/gl-accounts'
    | '/groups'
    | '/guarantors'
    | '/jobs'
    | '/loans'
    | '/offers'
    | '/products'
    | '/profile'
    | '/sponsorships'
    | '/staff'
    | '/statements'
    | '/tenders'
    | '/transfer'
    | '/withdraw'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/pin-setup'
    | '/p/$id'
    | '/admin/approvals'
    | '/admin/dashboard'
    | '/admin/loans'
    | '/admin/members'
    | '/admin/transactions'
    | '/business/$id'
    | '/dev/emails'
    | '/dev/statement'
    | '/loans/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/business'
    | '/cards'
    | '/class-groups'
    | '/gl-accounts'
    | '/groups'
    | '/guarantors'
    | '/jobs'
    | '/loans'
    | '/offers'
    | '/products'
    | '/profile'
    | '/sponsorships'
    | '/staff'
    | '/statements'
    | '/tenders'
    | '/transfer'
    | '/withdraw'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/pin-setup'
    | '/p/$id'
    | '/admin/approvals'
    | '/admin/dashboard'
    | '/admin/loans'
    | '/admin/members'
    | '/admin/transactions'
    | '/business/$id'
    | '/dev/emails'
    | '/dev/statement'
    | '/loans/apply'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_app/accounts'
    | '/_app/business'
    | '/_app/cards'
    | '/_app/class-groups'
    | '/_app/gl-accounts'
    | '/_app/groups'
    | '/_app/guarantors'
    | '/_app/jobs'
    | '/_app/loans'
    | '/_app/offers'
    | '/_app/products'
    | '/_app/profile'
    | '/_app/sponsorships'
    | '/_app/staff'
    | '/_app/statements'
    | '/_app/tenders'
    | '/_app/transfer'
    | '/_app/withdraw'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/pin-setup'
    | '/p/$id'
    | '/_app/'
    | '/_admin/admin/approvals'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/loans'
    | '/_admin/admin/members'
    | '/_admin/admin/transactions'
    | '/_app/business/$id'
    | '/_app/dev/emails'
    | '/_app/dev/statement'
    | '/_app/loans/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthPinSetupRoute: typeof AuthPinSetupRoute
  PIdRoute: typeof PIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pin-setup': {
      id: '/auth/pin-setup'
      path: '/auth/pin-setup'
      fullPath: '/auth/pin-setup'
      preLoaderRoute: typeof AuthPinSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/withdraw': {
      id: '/_app/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer': {
      id: '/_app/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenders': {
      id: '/_app/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof AppTendersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sponsorships': {
      id: '/_app/sponsorships'
      path: '/sponsorships'
      fullPath: '/sponsorships'
      preLoaderRoute: typeof AppSponsorshipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guarantors': {
      id: '/_app/guarantors'
      path: '/guarantors'
      fullPath: '/guarantors'
      preLoaderRoute: typeof AppGuarantorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gl-accounts': {
      id: '/_app/gl-accounts'
      path: '/gl-accounts'
      fullPath: '/gl-accounts'
      preLoaderRoute: typeof AppGlAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/class-groups': {
      id: '/_app/class-groups'
      path: '/class-groups'
      fullPath: '/class-groups'
      preLoaderRoute: typeof AppClassGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business': {
      id: '/_app/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/apply': {
      id: '/_app/loans/apply'
      path: '/apply'
      fullPath: '/loans/apply'
      preLoaderRoute: typeof AppLoansApplyRouteImport
      parentRoute: typeof AppLoansRoute
    }
    '/_app/dev/statement': {
      id: '/_app/dev/statement'
      path: '/dev/statement'
      fullPath: '/dev/statement'
      preLoaderRoute: typeof AppDevStatementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dev/emails': {
      id: '/_app/dev/emails'
      path: '/dev/emails'
      fullPath: '/dev/emails'
      preLoaderRoute: typeof AppDevEmailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/$id': {
      id: '/_app/business/$id'
      path: '/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof AppBusinessIdRouteImport
      parentRoute: typeof AppBusinessRoute
    }
    '/_admin/admin/transactions': {
      id: '/_admin/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminAdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/members': {
      id: '/_admin/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminAdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/loans': {
      id: '/_admin/admin/loans'
      path: '/admin/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof AdminAdminLoansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/approvals': {
      id: '/_admin/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminAdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminApprovalsRoute: typeof AdminAdminApprovalsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminLoansRoute: typeof AdminAdminLoansRoute
  AdminAdminMembersRoute: typeof AdminAdminMembersRoute
  AdminAdminTransactionsRoute: typeof AdminAdminTransactionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminApprovalsRoute: AdminAdminApprovalsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminLoansRoute: AdminAdminLoansRoute,
  AdminAdminMembersRoute: AdminAdminMembersRoute,
  AdminAdminTransactionsRoute: AdminAdminTransactionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppBusinessRouteChildren {
  AppBusinessIdRoute: typeof AppBusinessIdRoute
}

const AppBusinessRouteChildren: AppBusinessRouteChildren = {
  AppBusinessIdRoute: AppBusinessIdRoute,
}

const AppBusinessRouteWithChildren = AppBusinessRoute._addFileChildren(
  AppBusinessRouteChildren,
)

interface AppLoansRouteChildren {
  AppLoansApplyRoute: typeof AppLoansApplyRoute
}

const AppLoansRouteChildren: AppLoansRouteChildren = {
  AppLoansApplyRoute: AppLoansApplyRoute,
}

const AppLoansRouteWithChildren = AppLoansRoute._addFileChildren(
  AppLoansRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBusinessRoute: typeof AppBusinessRouteWithChildren
  AppCardsRoute: typeof AppCardsRoute
  AppClassGroupsRoute: typeof AppClassGroupsRoute
  AppGlAccountsRoute: typeof AppGlAccountsRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppGuarantorsRoute: typeof AppGuarantorsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLoansRoute: typeof AppLoansRouteWithChildren
  AppOffersRoute: typeof AppOffersRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSponsorshipsRoute: typeof AppSponsorshipsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppTendersRoute: typeof AppTendersRoute
  AppTransferRoute: typeof AppTransferRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDevEmailsRoute: typeof AppDevEmailsRoute
  AppDevStatementRoute: typeof AppDevStatementRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBusinessRoute: AppBusinessRouteWithChildren,
  AppCardsRoute: AppCardsRoute,
  AppClassGroupsRoute: AppClassGroupsRoute,
  AppGlAccountsRoute: AppGlAccountsRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppGuarantorsRoute: AppGuarantorsRoute,
  AppJobsRoute: AppJobsRoute,
  AppLoansRoute: AppLoansRouteWithChildren,
  AppOffersRoute: AppOffersRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSponsorshipsRoute: AppSponsorshipsRoute,
  AppStaffRoute: AppStaffRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppTendersRoute: AppTendersRoute,
  AppTransferRoute: AppTransferRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppIndexRoute: AppIndexRoute,
  AppDevEmailsRoute: AppDevEmailsRoute,
  AppDevStatementRoute: AppDevStatementRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthPinSetupRoute: AuthPinSetupRoute,
  PIdRoute: PIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
